//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightEntities3 : DbContext
    {
        public FlightEntities3()
            : base("name=FlightEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Ticket_Form> Ticket_Form { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
