//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int CID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Country { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string Alternate_Email { get; set; }
        public Nullable<long> phone_no { get; set; }
        public string Password { get; set; }
    }
}
