//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string Day { get; set; }
        public string Source { get; set; }
        public string Destinatiom { get; set; }
        public string Depature { get; set; }
        public string Arrival { get; set; }
        public string price { get; set; }
    }
}
